app:
  task-image-names:
    - ниска осветеност (1).png
    - ниска осветеност (2).png
    - осветно_(2).png
    - осветено_(тест).png
    - осветно_(1).png
    - средна осветеност (1).png
    - средна осветеност (3).png
    - средна осветеност (2).png

logging:
  file:
    name: logs/opencvUpdated.log
  logback:
    rollingpolicy:
      max-file-size: 10MB